"""Database models for the Trading Assistant."""

from datetime import datetime
from typing import Optional, List
from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Text, Boolean, JSON,
    ForeignKey, create_engine, Index
)
from sqlalchemy.orm import relationship, declarative_base
from enum import Enum

Base = declarative_base()


class Stock(Base):
    """
    Master list of stocks (Nifty 500 universe).
    Contains basic info and API tokens.
    """
    __tablename__ = "stocks"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Basic identifiers
    symbol = Column(String(50), nullable=False, unique=True, index=True)
    name = Column(String(200), nullable=False)
    isin = Column(String(20), nullable=True, unique=True)
    
    # Exchange info
    exchange = Column(String(10), default="NSE")
    nse_token = Column(String(20), nullable=True)  # Angel API token for NSE
    bse_token = Column(String(20), nullable=True)  # Angel API token for BSE
    bse_code = Column(String(10), nullable=True)   # BSE scrip code
    
    # Classification
    sector = Column(String(100), nullable=True)
    industry = Column(String(100), nullable=True)
    
    # Index membership flags
    is_nifty50 = Column(Boolean, default=False)
    is_nifty100 = Column(Boolean, default=False)
    is_nifty200 = Column(Boolean, default=False)
    is_nifty500 = Column(Boolean, default=True)
    
    # Status
    is_active = Column(Boolean, default=True)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    __table_args__ = (
        Index("idx_stock_sector", "sector"),
        Index("idx_stock_industry", "industry"),
    )
    
    def __repr__(self):
        return f"<Stock {self.symbol} ({self.name})>"


class TradeDirection(str, Enum):
    """Trade direction."""
    BUY = "BUY"
    SELL = "SELL"


class TradeStatus(str, Enum):
    """Status of a trade recommendation."""
    PENDING = "pending"
    EXECUTED = "executed"
    CANCELLED = "cancelled"
    EXPIRED = "expired"


class TradeRecommendation(Base):
    """
    Trade recommendations generated by the LLM.
    These are stored for learning and analysis.
    """
    __tablename__ = "trade_recommendations"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    # Stock info
    symbol = Column(String(50), nullable=False, index=True)
    exchange = Column(String(10), default="NSE")
    
    # Recommendation
    direction = Column(String(10), nullable=False)  # BUY or SELL
    entry_price = Column(Float, nullable=True)
    target_price = Column(Float, nullable=True)
    stop_loss = Column(Float, nullable=True)
    quantity = Column(Integer, nullable=True)
    
    # Analysis
    confidence = Column(Float, nullable=True)  # 0-1
    reasoning = Column(Text, nullable=True)  # LLM's reasoning
    technical_summary = Column(JSON, nullable=True)  # Technical indicators
    
    # Status
    status = Column(String(20), default=TradeStatus.PENDING.value)
    executed_at = Column(DateTime, nullable=True)
    executed_price = Column(Float, nullable=True)
    
    # Outcome (filled after trade closes)
    exit_price = Column(Float, nullable=True)
    exit_at = Column(DateTime, nullable=True)
    pnl = Column(Float, nullable=True)  # Profit/Loss
    pnl_pct = Column(Float, nullable=True)  # P&L percentage
    
    __table_args__ = (
        Index("idx_symbol_date", "symbol", "created_at"),
    )


class MarketSnapshot(Base):
    """
    Periodic snapshots of market data for analysis.
    """
    __tablename__ = "market_snapshots"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    
    symbol = Column(String(50), nullable=False, index=True)
    exchange = Column(String(10), default="NSE")
    
    # Price data
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    close = Column(Float)
    volume = Column(Integer)
    
    # Technical indicators (stored as JSON for flexibility)
    indicators = Column(JSON, nullable=True)
    
    __table_args__ = (
        Index("idx_snapshot_symbol_time", "symbol", "timestamp"),
    )


class ConversationMemory(Base):
    """
    Short-term conversation memory.
    Stores recent chat messages for context.
    """
    __tablename__ = "conversation_memory"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(String(100), nullable=False, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    
    role = Column(String(20), nullable=False)  # user, assistant, system
    content = Column(Text, nullable=False)
    
    # Optional extra_data
    extra_data = Column(JSON, nullable=True)
    
    __table_args__ = (
        Index("idx_session_time", "session_id", "timestamp"),
    )


class LongTermMemory(Base):
    """
    Long-term memory for persistent learnings.
    Stores insights, patterns, and user preferences.
    """
    __tablename__ = "long_term_memory"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Memory type
    memory_type = Column(String(50), nullable=False, index=True)
    # Types: "trade_outcome", "market_pattern", "user_preference", "strategy_insight"
    
    # Content
    key = Column(String(200), nullable=False, index=True)
    content = Column(Text, nullable=False)
    
    # Vector embedding for similarity search (stored as JSON array)
    embedding = Column(JSON, nullable=True)
    
    # Importance/relevance score (for memory pruning)
    importance = Column(Float, default=0.5)
    access_count = Column(Integer, default=0)
    last_accessed = Column(DateTime, nullable=True)
    
    __table_args__ = (
        Index("idx_memory_type_key", "memory_type", "key"),
    )


class TradingJournal(Base):
    """
    User's trading journal entries.
    For tracking actual trades and learnings.
    """
    __tablename__ = "trading_journal"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    # Trade details
    symbol = Column(String(50), nullable=False)
    direction = Column(String(10), nullable=False)
    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float, nullable=True)
    quantity = Column(Integer, nullable=False)
    
    # Dates
    entry_date = Column(DateTime, nullable=False)
    exit_date = Column(DateTime, nullable=True)
    
    # Outcome
    pnl = Column(Float, nullable=True)
    pnl_pct = Column(Float, nullable=True)
    
    # Notes
    entry_reason = Column(Text, nullable=True)
    exit_reason = Column(Text, nullable=True)
    lessons_learned = Column(Text, nullable=True)
    emotions = Column(String(50), nullable=True)  # How you felt during trade
    
    # Tags for filtering
    tags = Column(JSON, nullable=True)  # ["swing", "earnings", "breakout"]


class WatchlistItem(Base):
    """
    User's watchlist items.
    """
    __tablename__ = "watchlist"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    symbol = Column(String(50), nullable=False, unique=True)
    exchange = Column(String(10), default="NSE")
    token = Column(String(20), nullable=True)
    
    # Alert settings
    alert_above = Column(Float, nullable=True)
    alert_below = Column(Float, nullable=True)
    
    # Notes
    notes = Column(Text, nullable=True)
    
    # Priority for sorting
    priority = Column(Integer, default=0)
